[33mWARNING [0m selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (135.0.7049.95) detected in PATH at /opt/homebrew/bin/chromedriver might not be compatible with the detected chrome version (136.0.7103.116); currently, chromedriver 136.0.7103.113 is recommended for chrome 136.*, so it is advised to delete the driver in PATH and retry
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102f17490>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/64ae0e16804019feeafb068b80f925e7/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102f57770>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/64ae0e16804019feeafb068b80f925e7/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102f21bf0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/64ae0e16804019feeafb068b80f925e7/screenshot